version: '3'
services:

  # Build app from Dockerfile in same folder
  app:
    build: .
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=world
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example

  # Build the db as name db from the Dockerfile in the db folder
  # exposing the port if we want to run code outside a container
  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"